### PR TITLE
Add upload slicer salt package script

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@bpaniagua Current packages have been uploaded, new Preview (aka Nightly) package will be uploaded daily for all platforms

image

**Comment by bpaniagua** [comment]
Great Job, thanks! @jcfr

**Comment by jcfr** [comment]
> failed on linux

Error was that when executed from cronjob environment, the newer cmake binary were not in the PATH. It is now fixed in https://github.com/Slicer/DashboardScripts/commit/a959a21b79e333c0fb50b22d36414c837c4216d9

Error was:

```
CMake Error: cmake version 2.8.12.2
Usage: /usr/bin/cmake -E [command] [arguments ...]
Available commands:
[...]
```

Issue

**Comment by jcfr** [comment]
### Windows

* Upload summary is now log on windows and confirm it works:

```
Looking up SlicerSALT package in [D:/D/P/SSALT-0-build/Slicer-build]
Looking up SlicerSALT package in [D:/D/P/SSALT-0-build/Slicer-build] - SlicerSALT-1.1.0-2018-10-25-win-amd64.exe
Uploading [SlicerSALT-1.1.0-2018-10-25-win-amd64.exe] to [https://data.kitware.com/api/v1]
Uploading Item from SlicerSALT-1.1.0-2018-10-25-win-amd64.exe
File SlicerSALT-1.1.0-2018-10-25-win-amd64.exe exists in item, but with stale contents
Uploading [SlicerSALT-1.1.0-2018-10-25-win-amd64.exe] to [https://data.kitware.com/api/v1] - done
```

**Comment by jcfr** [comment]
Linux and macOs upload log will also be logged in their own file. https://github.com/Slicer/DashboardScripts/commit/1abf576210e240611c47da3a33f9349b17603eb3

**Pull request merged**
