### PR TITLE
factory-south-macos: Update nightly builds to use Qt 5.15.0

### PR DESCRIPTION
**Pull request by jamesobutler**
**UPDATE: Read https://github.com/Slicer/DashboardScripts/pull/27#issuecomment-635024624**
 
--------------------------------
This PR updates the dashboard script for Metroplex to use Qt 5.12.8. This PR is starting out as a draft since it is unclear how the stable builds of slicer and its extensions will continue to be built when the macOS build machine updates. Some updates required as part of building Qt 5.12.8 from source (accomplished by https://github.com/jcfr/qt-easy-build/pull/55)
Some potential options:
- Factory-south-macos be updated to macOS 10.13.6 (latest macOS High Sierra version)
- Xcode 9.4.1 installed (macOS 10.13 High Sierra SDK) Apple LLVM version 9.1.0 (clang-902.0.39.2)

- Factory-south-macos be updated to macOS 10.14.6 (latest macOS Mojave version)
- Xcode 10.3 installed (macOS 10.14 Mojave SDK) Apple LLVM version 10.0.1 (clang-1001.0.46.4)

- Slicer minimum deployment target updated to 10.12

Qt 5.12.8 supports the below configuration ([source](https://doc-snapshots.qt.io/qt5-5.12/supported-platforms.html))

| Platform | Architecture | Build Environment |
|-----------|-----------|--------|
|macOS 10.12, 10.13, 10.14| x86_64 and x86_64h | Xcode 10 (10.14 SDK), Xcode 9 (10.13 SDK)|

-------------------
Factory-south-macos is currently Mac OS X 10.11.6, El Capitan ([source](https://www.slicer.org/wiki/Documentation/Nightly/Developers/Factory#factory-south.kitware)) and using Qt 5.10.0.
Qt 5.10.0 supports the below configuration ([source](https://doc.qt.io/archives/qt-5.10/supported-platforms-and-configurations.html))

| Platform | Compiler | Notes |
|-----------|-----------|--------|
| macOS 10.11, 10.12, 10.13 (x86_64) | Clang as provided by Apple | Xcode 8.2 (macOS 10.11), Xcode 8.3.3 (macOS 10.12), Xcode 9 (macOS 10.13)|

### CODE REVIEW

**Comment by sjh26** [comment]
@jcfr How feasible is updating the OS on this factory?

**Comment by jcfr** [comment]
@thewtex  Will the update of factory-south-macos impact the ITK python release ?

**Comment by thewtex** [comment]
@jcfr thanks for checking -- should be fine to proceed.

**Comment by jamesobutler** [comment]
I've updated this PR to aim for updating the nightly builds to use Qt 5.15.0.

Qt 5.15.0 supports the below configuration ([source](https://doc-snapshots.qt.io/qt5-5.15/supported-platforms.html))

| Platform | Architecture | Build Environment |
|-----------|-----------|--------|
|macOS 10.13, 10.14, 10.15| x86_64 and x86_64h | Xcode 11 (10.15 SDK)|



- [ ] Update factory to macOS 10.15.5 (latest version)
- [ ] Install XCode 11.5 which comes with the macOS 10.15.4 SDK ([source](https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_5_release_notes)). XCode 11.5 is LLVM version 9.0.0 and Clang version 11.0.3 (clang-1103.0.32.62).
- [ ] Slicer minimum deployment target updated to 10.13

**Comment by sjh26** [comment]
@jcfr is currently working on the OS upgrade

**Comment by jcfr** [comment]
Latest update. See https://discourse.slicer.org/t/2020-06-09-macos-packages-will-not-be-available-until-build-machine-is-updated-to-macos-10-13-6/11935/5?u=jcfr

**Pull request merged**
