### PR TITLE
Update nightly builds to use Qt 5.12.4

### PR DESCRIPTION
**Pull request by jamesobutler**
This PR updates nightly builds to use Qt 5.12.4. 

Other updates to support Qt 5.12.4 QWebEngine [build requirements](https://doc.qt.io/qt-5.12/qtwebengine-platform-notes.html):
- For Windows builds, this requires an update to at least Visual Studio 2017 (v141 toolset)
- For Mac this requires macOS 10.12 or later.

I've updated the generators to Visual Studio 2019 which can continue to build Visual Studio 2015 builds with the included v140 toolset. You can also use Visual Studio 2019 to build Visual Studio 2017 builds with the included v141 toolset.

One reason this doesn't include switching to the Visual Studio v142 toolset is that ITK, at this time,  only supports v142 with [some caveats](https://discourse.itk.org/t/has-anyone-tried-to-build-visual-studio-c-2019/1561/6?u=dzenanz). See [ITK Supported compilers](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/SupportedCompilers.md) document.

From ToDo list in:
https://discourse.slicer.org/t/build-failure-windows/7322/37

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks a lot for working on this. Your changes for Windows platform look good to me.

**Comment by jcfr** [comment]
Thanks for the contribution

> For Mac this requires macOS 10.12 or later.

* Do we need to update the version of macOS (it is current 10.11.6) ? Since it already has `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk` available, isn't that sufficient.

If we upgrade the version of macOS, I anticipate it will be challenging to build the stable release extension associated with a build tree targeting 10.9

* To ensure packaging work as expected, we need to build Qt from source (without framework), this means a new branch should be added to https://github.com/jcfr/qt-easy-build/tree/5.11.2



> Linux

Where you able to locally build the image associated with https://github.com/Slicer/SlicerBuildEnvironment/pull/13 ?

**Comment by jamesobutler** [comment]
> Do we need to update the version of macOS (it is current 10.11.6) ? Since it already has `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk` available, isn't that sufficient.

Yes, I guess that's right. It requires macOS 10.12 to build QtWebEngine from source for that to be in Qt 5.12.4, but figured the target of the project using it would require an updated version. The build machine could continue being 10.11.6.

> To ensure packaging work as expected, we need to build Qt from source (without framework), this means a new branch should be added to https://github.com/jcfr/qt-easy-build/tree/5.11.2

Here is the link to the PR (https://github.com/jcfr/qt-easy-build/pull/54) that adds support to build Qt 5.12.4 for macOS so that you can use that as part of the build process. You will need to build this and add to the build machine prior to this PR being merged.

> Where you able to locally build the image associated with Slicer/SlicerBuildEnvironment#13 ?

I have not personally built this image, but updated the code similar to the last time Qt was updated here.

**Comment by jamesobutler** [comment]
*Clarification/Correction: To build Qt QWebEngine for Qt 5.12 for macOS, the build machine needs to have the following as stated in the [Qt WebEngine Platform Notes](https://doc.qt.io/qt-5.12/qtwebengine-platform-notes.html#macos)

> On macOS, the following are required:
> - macOS 10.12 or later
> - Xcode 8.3.3 or later
> - macOS 10.12 SDK or later

Therefore if the nightly build machine is also going to build Qt 5.12 w/ WebEngine from source it will need to be version 10.12.

**Comment by jamesobutler** [comment]
Closing this PR in favor of PRs that are specific to each platform as required upgrades will likely be done on a per platform basis. See #25, #26, #27.

**Pull request closed without merging**
